spring:
   profiles:
      active: dev

---

# common : spring boot configuration
spring:

   # devtools - live reload
   livereload:
      enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views
         suffix: .jsp

   # 



---

# dev profile : spring boot configuration
spring:
   config:
      active:
         on-profile: dev

   #datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.83:3307/webdb?characterEncoding=UTF-8&serverTimezone=UTC
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# production profile : spring boot configuration
spring:
   config:
      active:
         on-profile: production

   #datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.83:3307/webdb?characterEncoding=UTF-8&serverTimezone=UTC
      username: block
      password: block
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# server
server:
   port: 8080
   servlet:
      context-path: /mysite06
      encoding:
         charset: utf-8
         enabled: true
         force: false
         force-request: false
         force-response: false



---

# mybatis
mybatis:
   config-location:classpath:mybatis/configuration.xml

---

# logging





